// <auto-generated/>
// 全局 using 指令，由代码整理工具生成
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using JiebaNet.Segmenter;
global using Lucene.Net.Analysis;
global using Lucene.Net.Documents;
global using Lucene.Net.Store;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;
global using Octopus.SearchCore;
global using Octopus.SearchCore.Ext;
global using Octopus.SearchCore.Interfaces;
global using Octopus.SearchCore.TagSource;