<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AssemblyName>OctopusEx.SearchCore</AssemblyName>
        <RootNamespace>Octopus.SearchCore</RootNamespace>
        <AssemblyTitle>OctopusEx 全文搜索引擎</AssemblyTitle>
        <Description>基于 Lucene.NET 的中文全文搜索引擎，内置结巴分词，支持模糊搜索、多字段权重、Tag提取。</Description>
        <Company>Fatty Coder</Company>
        <Copyright>©2024-2025 Fatty Coder</Copyright>
        <VersionPrefix>1.2</VersionPrefix>
        <VersionSuffix>$([System.DateTime]::Now.ToString(`yyyy.MMdd`))</VersionSuffix>
        <Version>$(VersionPrefix).$(VersionSuffix)</Version>
        <FileVersion>$(Version)</FileVersion>
        <AssemblyVersion>$(VersionPrefix).$([System.DateTime]::Now.ToString(`yyyy.MMdd`))</AssemblyVersion>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>

        <!-- 程序集签名配置 -->
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>../octopus-key.snk</AssemblyOriginatorKeyFile>
        <DelaySign>false</DelaySign>
    </PropertyGroup>

    <!-- NuGet 包元数据 -->
    <PropertyGroup>
        <PackageId>OctopusEx.SearchCore</PackageId>
        <Authors>Fatty Coder</Authors>
        <RepositoryUrl>https://github.com/Fat-Snail/OctopusUtils</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>OctopusEx全文搜索;Lucene.NET;中文分词;结巴;OctopusEx.SearchCore</PackageTags>
        <PackageIcon>favicon.png</PackageIcon>
        <PackageReleaseNotes>OctopusEx 全文搜索引擎；Lucene.NET；中文分词；Tag提取；</PackageReleaseNotes>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\favicon.png" Link="favicon.png" PackagePath="\" />
    </ItemGroup>
    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="/"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00017" />
      <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="9.5.0" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Interfaces\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Octopus.Segment\Octopus.Segment.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="TagSource\tag_role.txt" />
      <EmbeddedResource Include="TagSource\tag_role.txt" />
      <None Remove="TagSource\tag_scene.txt" />
      <EmbeddedResource Include="TagSource\tag_scene.txt" />
    </ItemGroup>

</Project>
