// <auto-generated/>
// 全局 using 指令，由代码整理工具生成
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using JiebaNet.Segmenter;
global using JiebaNet.Segmenter.Common;
